sudo: required
services:
  - docker

before_install:
  - docker build -t superiqbal7/client-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true superiqbal7/client-test npm test -- --coverage

after_success:
  - docker build -t superiqbal7/multi-client ./client
  - docker build -t superiqbal7/multi-nginx ./nginx
  - docker build -t superiqbal7/multi-server ./server
  - docker build -t superiqbal7/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push superiqbal7/multi-client
  - docker push superiqbal7/multi-nginx
  - docker push superiqbal7/multi-worker
  - docker push superiqbal7/multi-server

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-126930600597'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KE
